update_fastlane

default_platform(:android)
sign_properties = {
         "android.injected.signing.store.file" => ENV["KEYSTORE_FILENAME"],
         "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
         "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
         "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"],
         }
platform :android do
  before_all do
  ENV["FLAVOR"] = "VALRT"
  end
  desc "Builds the debug code"
  lane :buildDebug do
    gradle(
     task: "assemble",
     flavor: ENV["FLAVOR"],
     build_type: "Debug",
     print_command: true,
     properties: sign_properties
    )
  end

  desc "Builds the release code"
  lane :buildRelease do
    gradle(
      task: "assemble",
      flavor: ENV["FLAVOR"],
      build_type: "Release",
      print_command: true,
      properties: sign_properties
    )
  end
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    upload_to_play_store(track: 'internal', apk: 'app/build/outputs/apk/VALRT/release/app-VALRT-release.apk')
  end

  desc "Promote Internal to Alpha"
  lane :promote_internal_to_alpha do
    upload_to_play_store(track: 'internal', track_promote_to: 'alpha')
  end

  desc "Promote Alpha to Beta"
  lane :promote_alpha_to_beta do
    upload_to_play_store(track: 'alpha', track_promote_to: 'beta')
  end

  desc "Promote Beta to Production"
  lane :promote_beta_to_production do
    upload_to_play_store(track: 'beta', track_promote_to: 'production')
  end

end
